site_name: Introducción a Fortinet, ciberseguridad de última generación
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
  icon:
    logo: simple/fortinet
    repo: simple/git
  favicon: images/fortinet-favicon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
nav:
    - Home: index.md
    - Pre-proyecto: pre-proyecto.md
    - Primeros pasos:
        - 'Unboxing': 'unboxing.md'
    - Demo: demo.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox
  - search
  - mkdocs-asciinema
repo_url: https://github.com/adriasir123/pi-fortinet
repo_name: adriasir123/pi-fortinet