site_name: PI Fortinet
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
  icon:
    logo: material/linux
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
nav:
    - Home: index.md
    - 2º ASIR 19/20:
        - 'Práctica 6: Auditoría de bases de datos': '2asir19-20/auditoria-practica-bd.md'
        - 'Práctica 4 BD: Interconexión de Servidores de Bases de Datos': '2asir19-20/database-interconnection.md'
        - 'Práctica: Despliegue de CMS java': '2asir19-20/java-webapp.md'
        - 'Práctica: Métricas, logs y monitorización': '2asir19-20/metrics-logs-monitoring.md'
        - 'Práctica 3 BD (PI): Gestión de usuarios, privilegios y roles': '2asir19-20/p3-bd-pi-oracle.md'
        - 'Práctica 5 BD draft: Gestión del almacenamiento (individual)': '2asir19-20/p5-bd-individua-draft.md'
        - 'Práctica 5 BD: Gestión del almacenamiento (individual)': '2asir19-20/p5-bd-individual.md'
        - 'Práctica: Proxy, proxy inverso y balanceadores de carga': '2asir19-20/proxy-practica.md'
        - 'Práctica servicios: Ejecución de scripts PHP y Python. Rendimiento': '2asir19-20/rendimiento-ejec-php-python.md'
        - 'Tema 6: Las formas jurídicas de la empresa': '2asir19-20/t4-formas-juridicas.md'
        - 'Tarea 7 Cloud: Hosting': '2asir19-20/t7-cloud-hosting.md'
        - 'Tarea 8 Cloud:  Instalación de app python (Mezzanine)': '2asir19-20/t8-cloud-app-python.md.md'
        - 'Práctica: Usuarios, grupos y ACLs en LDAP': '2asir19-20/usuarios-grupos-acl-ldap.md'
    - 2º ASIR 20/21:
        - 'Compilación de un programa en C': '2asir20-21/compilacion-programaC-con-makefile.md'
        - 'Documentación servidores físicos': '2asir20-21/doc-servidores-fisicos.md'
        - 'Ejercicio: Cifrado simétrico con gpg+openssl': '2asir20-21/ejercicio-cifrado-simetrico-gpg-openssl.md'
        - 'Ejercicios de manejo de módulos': '2asir20-21/ejs-modulos-kernel.md'
        - 'Práctica: Instalación de Debian 10': '2asir20-21/instalacion-debian-10.md'
        - 'Ejercicio 4: Mapeo URLs': '2asir20-21/mapeo-urls-sistema-ficheros.md'
        - 'Práctica 3: Integridad, firmas y autenticación': '2asir20-21/p3-integridad-firmas-autenticacion.md'
        - 'Práctica: Cifrado asimétrico con gpg y openssl': '2asir20-21/practica-cifrado-asimetrico-gpg-openssl.md'
        - 'Práctica infantil de PL/SQL': '2asir20-21/practica-infantil-plsql.md'
        - 'Prácticas de la UD1 SEG': '2asir20-21/practicas-ud1-seg.md'
        - 'Tarea: Creación de un sistema automatizado de instalación': '2asir20-21/tarea-creacion-sistema-automatizado-instalacion.md'
    - 2º ASIR 21/22:
        - SRI:
            - Vagrant y Ansible:
                - 'Ejercicio 1: Playbook sencillo': 'sri/ej1-playbook-sencillo.md'
                - 'Ejercicio 2: router NAT vagrant': 'sri/ej2-router-nat-vagrant.md'
                - 'Ejercicio 3: Configuración escenario router NAT': 'sri/ej3-config-escenario-router-nat.md'
            - DHCP:
                - 'Ejercicio 1': 'sri/ej1-instalar-configurar-dhcp.md'
                - 'Ejercicio 2: reservas': 'sri/ej2-reserva-dhcp.md'
                - 'Práctica': 'sri/practica-servidor-dhcp.md'
            - HTTP:
                - 'Ejercicio 1: Mapeo de URLs': 'sri/ej1-mapeo-urls-al-sistema-ficheros.md'
                - 'Ejercicio 2: Control de acceso': 'sri/ej2-control-acceso-autenticacion-autorizacion.md'
                - 'Ejercicio 3: .htaccess con Apache': 'sri/ej3-apache-.htaccess.md'
                - 'Ejercicio 4: Módulos en Apache': 'sri/ej4-modulos-apache.md'
                - 'Ejercicio 5: VPS': 'sri/ej5-vps.md'
                - 'Ejercicio 6: Apache proxy inverso': 'sri/ej6-apache-proxy-inverso.md'
                - 'Práctica: LEMP en VPS': 'sri/practica3-LEMP-VPS.md'
            - DNS:
                - 'Ejercicio 1: bind9': 'sri/ej1-instalar-configurar-bind9.md'
                - 'Ejercicio 2: Slave DNS': 'sri/ej2-instalar-configurar-slave.md'
                - 'Ejercicio 3: Delegación subdominios': 'sri/ej3-delegacion-subdominio-bind9.md'
                - 'Práctica: DNS+Web+BD en escenario': 'sri/practica-web-bd-dns-escenario.md'
            - HTTPS (1ª Parte):
                - 'Práctica: HTTPS en VPS': 'sri/practica-https-vps.md'
            - HTTP (2ª Parte):
                - 'Práctica: Aumento rendimiento web': 'sri/practica-aumento-rendimiento-web.md'
            - Correo:
                - 'Ejercicios en escenario libvirt': 'sri/ejercicios-correo.md'
                - 'Práctica: Servidor de correos en VPS': 'sri/practica-servidor-correo.md'
            - HA Clusters:
                - 'Práctica': 'sri/practica-cluster-ha.md'
        - IAW:
            - 'ej1-pull-request': 'iaw/2021-09-22-ej1-pull-request.md'
            - 'app-web-estatica': 'iaw/2021-10-5-implantacion-despliegue-aplicacion-web-estatica.md'
            - 'ej2-pr-pag-compañero': 'iaw/2021-10-14-ej2-pr-pag-compañero.md'
            - PHP:
                - 'Ejercicio 1: phpMyAdmin': 'iaw/ej1-phpmyadmin.md'
                - 'Ejercicio 2: BookMedik': 'iaw/ej2-bookmedik.md'
                - 'Ejercicio 3: php-fpm': 'iaw/ej3-phpfpm.md'
                - 'Práctica 1: Apps PHP': 'iaw/practica1-implantacion-apps-php.md'
                - 'Práctica 2: Instalación/migración de apps a VPS': 'iaw/practica2-instalacion-migracion-apps-PHP-en-VPS.md'
            - Python:
                - 'Ejercicio 1: Apache + mod_wsgi': 'iaw/ej1-apps-flask-apache2-mod_wsgi.md'
                - 'Ejercicio 2: Apache/Nginx + Gunicorn': 'iaw/ej2-apache2-gunicorn.md'
                - 'Ejercicio 3: Apache/Nginx + uWSGI': 'iaw/ej3-apache-uwsgi.md'
                - 'Práctica: Despliegue python': 'iaw/practica-despliegue-apps-python.md'
                - 'Práctica: CMS Python': 'iaw/practica-cms-python.md'
            - Java:
                - 'Práctica: CMS Java': 'iaw/practica-cms-java.md'
            - Docker:
                - 'Ejercicios': 'iaw/ejs-docker.md'
                - 'Práctica: BookMedik en Docker': 'iaw/practica-docker-php.md'
                - 'Práctica: Django tutorial en Docker': 'iaw/practica-docker-python.md'
        - SAD:
            - 'Criptografía 1: Cifrado asímetrico': 'sad/practica-cifrado-asimetrico-gpg-openssl.md'
            - 'Criptografía 2: Firmas': 'sad/practica-integridad-firmas-autenticacion.md'
            - 'Práctica: VPN': 'sad/practica-vpn-sad.md'
            - Cortafuegos:
                - 'Ejercicio 1 iptables: por nodo': 'sad/ej1-iptables-nodo.md'
                - 'Ejercicio 1 nftables: por nodo': 'sad/ej1-nftables-nodo.md'
                - 'Ejercicio 2 iptables: perimetral': 'sad/ej2-iptables-perimetral.md'
                - 'Ejercicio 2 nftables: perimetral': 'sad/ej2-nftables-perimetral.md'
                - 'Práctica iptables: perimetral escenario': 'sad/perimetral-iptables-escenario.md'
        - 'Escenario libvirt': 'practica-escenario-libvirt.md'
    - 2º ASIR 22/23:
        - ASO:
            - 'Instalación Debian 11': 'aso/instalacion_debian11.md'
            - 'Instalación Debian 11 preseed': 'aso/debian11_automatico.md'
            - 'Ejercicios de paquetería': 'aso/ejercicios-paqueteria.md'
            - 'Montaje NFS systemd': 'aso/systemd-montaje-nfs.md'
            - Kernel:
                - 'Teoría': 'aso/teoria-kernel.md'
                - 'Ejercicios de módulos': 'aso/ejercicios-de-modulos.md'
                - 'Ejercicios de parámetros': 'aso/ejercicios-parametros-kernel.md'
                - 'Compilación programas C': 'aso/compilacion-programas-c.md'
                - 'Compilación de Kernel': 'aso/compilacion-kernel.md'
            - Red Hat:
                - 'Migración CentOS': 'aso/migracion-centos.md'
            - 'Recolección de logs journald': 'aso/recoleccion-logs-journald.md'
            - OpenLDAP:
                - 'Práctica inicial': 'aso/ldap-inicial.md'
                - 'LDAPs': 'aso/ldaps.md'
        - BD:
            - 'Prueba inicial': 'bd/prueba-inicial.md'
            - 'Práctica 1: servidores y clientes': 'https://www.grupalesbdc.ga/p1-servidores-clientes/intro'
            - 'Práctica 2: interconexiones': 'bd/p2-interconexion-bd.md'
            - 'Examen prácticas 1 y 2': 'bd/examen-practicas-1-2.md'
            - 'Práctica 3: pequeña PL/SQL': 'bd/p3-pequeña-plsql.md'
            - 'Práctica 4: grupal PL/SQL': 'https://www.grupalesbdc.ga/p4-grupal-plsql/intro'
            - 'Examen prácticas 3 y 4': 'bd/examen-practicas-3-4.md'
            - 'Práctica 5 usuarios': 'https://www.grupalesbdc.ga/p5-usuarios/intro'
            - 'Examen prácticas 5 y 6': 'bd/examen-practicas-5-6.md'
        - HLC:
            - Virtualización en Linux:
                - 'Taller 1': 'hlc/taller1-virtualizacion.md'
                - 'Taller 2': 'hlc/taller2-virtualizacion.md'
                - 'Taller 3': 'hlc/taller3-virtualizacion.md'
                - 'Taller 4': 'hlc/taller4-virtualizacion.md'
                - 'Taller 5': 'hlc/taller5-virtualizacion.md'
                - 'Taller 6': 'hlc/taller6-virtualizacion.md'
                - 'Práctica': 'hlc/practica-virtualizacion.md'
            - OpenStack:
                - 'Taller 1': 'hlc/taller1-cliente-vpn.md'
            - Kubernetes:
                - 'Ejercicio 1: minikube y kubectl': 'hlc/ejercicio1-minikube-kubectl.md'
                - 'Taller 1: pods': 'hlc/taller1-pods.md'
                - 'Taller 2: ReplicaSet': 'hlc/taller2-replicaset.md'
    - OpenWebinars:
        - 'SQL desde Cero': 'openwebinars/sql-desde-cero.md'
        - 'Fundamentos de PL/SQL': 'openwebinars/fundamentos-plsql.md'
    - C1:
        - 'Essay: describing a place': 'c1/describing-place-essay.md'
        - 'Outline: injustice case': 'c1/injustice-case-outline.md'
        - 'Essay: meaningless activities': 'c1/leisure-time-meaningless-activities.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox
  - search
  - mkdocs-asciinema