site_name: Introducción a Fortinet, ciberseguridad de última generación
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
  icon:
    logo: simple/fortinet
    repo: simple/git
  favicon: images/fortinet-favicon.svg
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
nav:
    - Inicio: index.md
    - Pre-proyecto: pre-proyecto.md
    - Objetivos: objetivos.md
    - Conceptos:
        - '¿Qué es un firewall?': 'conceptos/que-es-un-firewall.md'
        - 'Historia': 'conceptos/historia.md'
        - 'Tipos': 'conceptos/tipos.md'
        - 'Firewall hardware VS software': 'conceptos/firewall-hardware-vs-software.md'
    - Primeros pasos:
        - 'Unboxing': 'unboxing.md'
        - 'Paneles': 'paneles.md'
        - 'Reseteo': 'reseteo.md'
        - 'Acceso': 'acceso.md'
        - 'Salida a Internet': 'salida-a-internet.md'
    - Interfaz web: interfaz-web.md
    - CLI: cli.md
    - Demo:
        - 'Escenario': 'demo/escenario.md'
        - 'Preparación de la Raspberry': 'demo/preparacion-raspberry.md'
        - 'Salida a Internet': 'https://pi.adrianj.eu/salida-a-internet'
    - Conclusiones: conclusiones.md
    - Dificultades: dificultades.md
    - Bibliografía: bibliografia.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adriasir123
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adrian-jaramillo-rodriguez/
plugins:
  - glightbox
  - search
  - mkdocs-asciinema
repo_url: https://github.com/adriasir123/pi-fortinet
repo_name: adriasir123/pi-fortinet
copyright: GNU General Public License v3.0 &copy; 2023 Adrián Jaramillo Rodríguez